apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
data:
  DB_HOST: "alex-counter-service-postgres.c360efet38pa.eu-west-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "counter"
  DB_USER: "counter"
  OTEL_SERVICE_NAME: "counter-backend"
  OTEL_ENV: "prod"
  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://adot-collector.prod.svc.cluster.local:4318"
  FRONTEND_URL: "k8s-prod-counters-962591410f-519976047.eu-west-2.elb.amazonaws.com"
